import React, { useState, useEffect, useRef } from 'react';
import { Mic, Send, Users, BarChart3, ShieldAlert, LogOut, MessageSquare, List, Sparkles, TrendingUp, AlertCircle, CheckCircle2, Share2 } from 'lucide-react';

/**
 * PROJECT: CHILLBOYZ AGENTIC POKER (FINAL ARCHITECT EDITION)
 * OWNER: KT (Senior Software Architect)
 * FEATURES: Gemini 1.5 Flash Brain, AI-First UI, WhatsApp Reporting
 */

const PLAYERS = ["Anji", "KT", "Purna K", "Purna S", "Srini", "Kishore"];
const GLOBAL_PASS = "1234"; 

export default function App() {
  const [user, setUser] = useState<{id: string, role: string} | null>(null);
  const [loginId, setLoginId] = useState("");
  const [pass, setPass] = useState("");
  const [view, setView] = useState<'chat' | 'table'>('chat');
  const [scores, setScores] = useState<Record<string, number>>(PLAYERS.reduce((acc, p) => ({ ...acc, [p]: 0 }), {}));
  const [rebuys, setRebuys] = useState<Record<string, number>>(PLAYERS.reduce((acc, p) => ({ ...acc, [p]: 0 }), {}));
  const [messages, setMessages] = useState<{role: 'user' | 'ai', text: string}[]>([
    {role: 'ai', text: "Namaste KT Mama! I'm your ChillBoyz Agent. Who's winning today? Just say 'Srini 50' or 'Kishore rebuy'."}
  ]);
  const [input, setInput] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const chatEndRef = useRef<null | HTMLDivElement>(null);

  // Auto-scroll chat to bottom
  useEffect(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), [messages]);

  // --- BUSINESS LOGIC ---
  const handleAction = (player: string, action: 'score' | 'rebuy', value?: number) => {
    const matchedPlayer = PLAYERS.find(p => p.toLowerCase() === player.toLowerCase());
    if (!matchedPlayer) return "Player not found, Mama!";

    if (action === 'rebuy') {
      setRebuys(prev => ({ ...prev, [matchedPlayer]: prev[matchedPlayer] + 20 }));
      return `Done! Added $20 rebuy for ${matchedPlayer}.`;
    } else if (action === 'score' && value !== undefined) {
      setScores(prev => ({ ...prev, [matchedPlayer]: value }));
      return `Got it! Set ${matchedPlayer}'s score to ${value}.`;
    }
    return "I'm confused, try again.";
  };

  const getBalance = () => {
    const wins = Object.values(scores).reduce((a, b) => a + b, 0);
    const buyins = Object.values(rebuys).reduce((a, b) => a + b, 0);
    return wins - buyins;
  };

  // --- WHATSAPP REPORT ---
  const shareToWhatsApp = () => {
    const date = new Date().toLocaleDateString();
    let report = `*♠️ CHILLBOYZ POKER REPORT (${date}) ♠️*\n`;
    report += `--------------------------------\n`;
    PLAYERS.forEach(p => {
      const net = scores[p] - rebuys[p];
      report += `${p}: ${net > 0 ? "+" : ""}${net} (W:${scores[p]}, R:${rebuys[p]})\n`;
    });
    report += `--------------------------------\n`;
    report += `*Net Balance:* ${getBalance()}\n`;
    report += `*Status:* ${getBalance() === 0 ? "✅ SETTLED" : "❌ UNBALANCED"}\n`;
    report += `--------------------------------\n`;
    report += `_Generated by ChillBoyz AI Agent_`;

    window.open(`https://wa.me/?text=${encodeURIComponent(report)}`, '_blank');
  };

  // --- AGENTIC BRAIN (GEMINI 1.5 FLASH) ---
  const callAgent = async (text: string) => {
    if (!text.trim()) return;
    setMessages(prev => [...prev, {role: 'user', text}]);
    setInput("");
    setIsThinking(true);

    const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
    const prompt = `You are the ChillBoyz Poker Manager. Players: ${PLAYERS.join(", ")}. 
    Current Input: "${text}". 
    Extract player name and action. 
    If 'rebuy' or 'plus 20' or 'lost', action='rebuy'. If a specific number is given for a player, action='score' and value=number. 
    Return JSON ONLY: {"player": "Name", "action": "score"|"rebuy", "value": number, "reply": "A short witty reply in English"}`;

    try {
      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
      });
      const data = await res.json();
      const cleanJson = JSON.parse(data.candidates[0].content.parts[0].text.replace(/```json|```/g, ""));
      
      const statusMsg = handleAction(cleanJson.player, cleanJson.action, cleanJson.value);
      setMessages(prev => [...prev, {role: 'ai', text: cleanJson.reply || statusMsg}]);
    } catch (e) {
      setMessages(prev => [...prev, {role: 'ai', text: "Sorry Mama, I didn't get that. Try 'Srini 100' or 'Kishore rebuy'"}]);
    } finally {
      setIsThinking(false);
    }
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-[#050505] text-white flex items-center justify-center p-6">
        <div className="w-full max-w-sm bg-[#111] border border-white/5 p-10 rounded-[3rem] shadow-2xl text-center">
          <div className="w-20 h-20 bg-blue-600 rounded-[2rem] flex items-center justify-center mx-auto mb-6 shadow-xl shadow-blue-600/20 rotate-6">
            <Sparkles size={40} className="text-white" />
          </div>
          <h1 className="text-3xl font-black italic tracking-tighter mb-1">CHILLBOYZ</h1>
          <p className="text-[10px] text-zinc-600 font-bold uppercase tracking-widest mb-8 text-center">Agentic AI Manager</p>
          <div className="space-y-4">
            <input placeholder="Name (e.g. KT)" className="w-full bg-zinc-900 p-5 rounded-2xl border-none outline-none focus:ring-2 ring-blue-600" onChange={e=>setLoginId(e.target.value)} />
            <input type="password" placeholder="Password (1234)" className="w-full bg-zinc-900 p-5 rounded-2xl border-none outline-none focus:ring-2 ring-blue-600" onChange={e=>setPass(e.target.value)} />
            <button onClick={() => (loginId && pass === GLOBAL_PASS) && setUser({id: loginId, role: loginId.toUpperCase()==='KT'?'admin':'player'})} className="w-full bg-blue-600 p-5 rounded-2xl font-black uppercase tracking-widest hover:scale-95 transition-all shadow-lg shadow-blue-600/30">Launch Agent</button>
          </div>
          <p className="mt-8 text-[9px] text-zinc-700 uppercase font-bold leading-tight">Notice: Point-scoring only. No real money gambling.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100 flex flex-col max-w-lg mx-auto border-x border-white/5 shadow-2xl shadow-blue-900/10">
      {/* Header */}
      <header className="p-6 bg-black/50 backdrop-blur-xl border-b border-white/5 flex justify-between items-center sticky top-0 z-50">
        <div>
          <h2 className="text-lg font-black text-blue-500 italic flex items-center gap-2"><Sparkles size={18}/> CHILLBOYZ</h2>
          <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest">Balance: {getBalance()}</p>
        </div>
        <div className="flex gap-4 bg-white/5 p-1.5 rounded-2xl border border-white/5">
           <button onClick={()=>setView('chat')} className={`p-2 rounded-xl transition-all ${view==='chat'?'bg-blue-600 text-white shadow-lg':'text-zinc-600'}`}><MessageSquare size={20}/></button>
           <button onClick={()=>setView('table')} className={`p-2 rounded-xl transition-all ${view==='table'?'bg-blue-600 text-white shadow-lg':'text-zinc-600'}`}><List size={20}/></button>
           <button onClick={()=>setUser(null)} className="p-2 text-red-900/40"><LogOut size={20}/></button>
        </div>
      </header>

      {/* Main View Area */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-hide pb-32">
        {view === 'chat' && (
          <>
            {messages.map((m, i) => (
              <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'} animate-in slide-in-from-bottom-2 duration-300`}>
                <div className={`max-w-[85%] p-5 rounded-[2.2rem] text-sm font-medium shadow-xl ${m.role === 'user' ? 'bg-blue-600 text-white rounded-tr-none' : 'bg-[#18181b] text-zinc-200 rounded-tl-none border border-white/5'}`}>
                  {m.text}
                </div>
              </div>
            ))}
            {isThinking && <div className="text-[10px] text-blue-500 animate-pulse font-black uppercase tracking-widest pl-2">Agent is thinking...</div>}
            <div ref={chatEndRef} />
          </>
        )}

        {view === 'table' && (
          <div className="space-y-3 animate-in fade-in duration-500">
            {PLAYERS.map(p => (
              <div key={p} className="bg-zinc-900/40 border border-white/5 p-5 rounded-[2rem] flex justify-between items-center hover:border-blue-500/20 transition-all">
                <div className="flex flex-col">
                  <span className="font-bold text-zinc-200">{p}</span>
                  <span className="text-[9px] font-black text-zinc-600 uppercase">Live Stats</span>
                </div>
                <div className="flex gap-4 items-center">
                  <button onClick={() => handleAction(p, 'rebuy')} className="text-[10px] font-black text-red-500 bg-red-500/10 px-3 py-1.5 rounded-xl border border-red-500/10 active:scale-90 transition-all">-${rebuys[p]}</button>
                  <input 
                    type="number" 
                    value={scores[p] || ""} 
                    onChange={e => handleAction(p, 'score', parseInt(e.target.value))}
                    className="w-16 bg-zinc-800/50 p-2 rounded-xl text-center font-mono text-green-500 border border-white/5 outline-none focus:ring-1 ring-blue-500 transition-all"
                  />
                </div>
              </div>
            ))}
            
            <div className={`mt-8 p-10 rounded-[3rem] border-2 text-center transition-all duration-700 ${getBalance() === 0 ? 'border-green-500/20 bg-green-500/5 text-green-500' : 'border-red-500/20 bg-red-500/5 text-red-500'}`}>
               <p className="text-[10px] font-black uppercase opacity-40 mb-1">Session Result</p>
               <h1 className="text-7xl font-black tracking-tighter">{getBalance()}</h1>
               <div className="flex justify-center mt-4">
                  {getBalance() === 0 ? <CheckCircle2 size={24} className="animate-bounce"/> : <AlertCircle size={24} className="animate-pulse"/>}
               </div>
            </div>

            <button 
              onClick={shareToWhatsApp}
              className="w-full mt-6 bg-green-600 hover:bg-green-500 p-5 rounded-[2.5rem] font-black text-sm uppercase tracking-widest flex items-center justify-center gap-3 shadow-xl shadow-green-900/20 active:scale-95 transition-all text-white"
            >
              <Share2 size={20} /> Share WhatsApp Report
            </button>
          </div>
        )}
      </div>

      {/* Floating Action Bar */}
      <div className="p-6 bg-gradient-to-t from-black via-black/90 to-transparent fixed bottom-0 left-0 right-0 max-w-lg mx-auto">
        <div className="bg-zinc-900/90 backdrop-blur-2xl p-2 rounded-[3rem] border border-white/10 flex items-center shadow-2xl group focus-within:ring-2 ring-blue-600/50">
          <input 
            value={input}
            onChange={e=>setInput(e.target.value)}
            onKeyDown={e=> e.key === 'Enter' && callAgent(input)}
            placeholder="Type 'Srini 100' or 'KT rebuy'..." 
            className="flex-1 bg-transparent p-4 outline-none text-sm font-medium"
          />
          <button onClick={()=>callAgent(input)} className="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center hover:scale-95 transition-all shadow-lg shadow-blue-600/40 text-white">
            <Send size={18} />
          </button>
        </div>
        <p className="text-[8px] text-center text-zinc-800 mt-4 uppercase font-black tracking-[0.4em]">
          Engineered by KT Agentic Systems 2026
        </p>
      </div>
    </div>
  );
}
